name: Pull Request Template
description: Template for creating a pull request
body:
    - type: markdown
      attributes:
          value: |
              ### What issue does this PR address?

              - Please link to the issue here.

    - type: textarea
      id: issue_link
      attributes:
          label: Issue Link
          description: Provide the issue number or link to the related issue.
          placeholder: e.g., #123

    - type: markdown
      attributes:
          value: |
              ### Changes Proposed

              - Provide a detailed list or description of the changes introduced in this PR.

    - type: textarea
      id: changes_proposed
      attributes:
          label: Changes Proposed
          description: Describe the changes made in this PR.
          placeholder: Detailed description of changes.

    - type: markdown
      attributes:
          value: |
              ### Screenshots

              - If applicable, add screenshots to help explain your proposed changes.

    - type: textarea
      id: screenshots
      attributes:
          label: Screenshots
          description: Provide any screenshots if applicable.
          placeholder: Upload screenshots here.

    - type: markdown
      attributes:
          value: |
              ### Additional Context

              - Add any other context or information about the changes here.

    - type: textarea
      id: additional_context
      attributes:
          label: Additional Context
          description: Provide any additional information about the changes.
          placeholder: Additional context or information.
