queue_rules:
    - name: default
      batch_size: 8
      batch_max_wait_time: 60 s
      checks_timeout: 10800 s
      merge_method: squash
      commit_message_template: |
          {{ title }} (#{{ number }})

          {% for commit in commits %}
          * {{ commit.commit_message }}
          {% endfor %}
      queue_conditions:
          # TODO: Add "#approved-reviews-by >= 1" for later (not needed for now)
          - "check-success=target-branch-check"
      merge_conditions: []

pull_request_rules:
    - name: feature-to-unstable
      conditions:
          - base=unstable
          - "check-success=license/cla"
          - "check-success=target-branch-check"
      actions:
          queue:
              name: default
              commit_message_template: |
                  {{ title }}

    - name: unstable-to-stable
      conditions:
          - base=stable
          - "check-success=license/cla"
          - "check-success=target-branch-check"
      actions:
          merge:
              method: merge
