queue_rules:
    - name: default
      batch_size: 8
      batch_max_wait_time: 60 s
      checks_timeout: 10800 s
      merge_method: squash
      commit_message_template: |
          {{ title }} (#{{ number }})

          {% for commit in commits %}
          * {{ commit.commit_message }}
          {% endfor %}
      queue_conditions:
          # TODO: Add "#approved-reviews-by >= 1" for later (not needed for now)
          - "check-success=license/cla"
          - "check-success=target-branch-check"
      merge_conditions:
          - "check-success=test-suite-success"
          - "check-success=local-testnet-success"

pull_request_rules:
    - name: Comment on bugfix/emergency PRs
      conditions:
          - title~=^bugfix
          - title~=^emergency
      actions:
          comment:
              message: |
                  This pull request has been prefixed with `bugfix` or `emergency`. Please review if it can be merged directly to `stable`.

    - name: default
      conditions:
          - base=stable OR base=unstable
          - "check-success=license/cla"
          - "check-success=target-branch-check"
      actions:
          queue:
              name: default
              merge_conditions:
                  - "check-success=test-suite-success"
                  - "check-success=local-testnet-success"
