queue_rules:
    - name: default
      batch_size: 8
      batch_max_wait_time: 60s
      checks_timeout: 10800s
      commit_message_template: |
          {{ title }} (#{{ number }})

          {% for commit in commits %}
          * {{ commit.commit_message }}
          {% endfor %}
      queue_conditions:
          # TODO: Add "#approved-reviews-by >= 1" for later (not needed for now)
          - "check-success=license/cla"
          - "check-success=target-branch-check"
      merge_conditions: []
      speculative_checks: 5

    - name: merge-into-unstable
      conditions:
          - base=unstable
      actions:
          merge:
              method: squash

    - name: merge-into-stable
      conditions:
          - base=stable
      actions:
          merge:
              method: merge

    - name: merge-into-feature
      conditions:
          - base=**/*
          - base!=stable
          - base!=unstable
