queue_rules:
    - name: default
      batch_size: 8
      batch_max_wait_time: 60 s
      checks_timeout: 10800 s
      merge_method: squash
      commit_message_template: |
          {{ title }} (#{{ number }})

          {% for commit in commits %}
          * {{ commit.commit_message }}
          {% endfor %}
      queue_conditions:
          #   - "#approved-reviews-by >= 1"
          - "check-success=license/cla"
          - "check-success=target-branch-check"
      merge_conditions: []
# queue_rules:
#     - name: default
#       batch_size: 8
#       batch_max_wait_time: 60s
#       checks_timeout: 10800s
#       queue_conditions:
#           # TODO: Add "#approved-reviews-by >= 1" for later (not needed for now)
#           - "check-success=license/cla"
#           - "check-success=target-branch-check"
#       merge_conditions: []
#       speculative_checks: 5

# pull_request_rules:
#     - name: queue-feature-to-unstable
#       conditions:
#           - base=unstable
#           - "check-success=license/cla"
#           - "check-success=target-branch-check"
#       actions:
#           queue:
#               name: default
#               commit_message_template: |
#                   {{ title }}
#               merge_method: squash

#     - name: queue-unstable-to-stable
#       conditions:
#           - base=stable
#           - "check-success=license/cla"
#           - "check-success=target-branch-check"
#       actions:
#           queue:
#               name: default
#               commit_message_template: |
#                   {{ title }} (#{{ number }})
#               merge_method: merge

#     - name: queue-feature-to-feature
#       conditions:
#           - base~=^feature/.*
#           - head~=^feature/.*
#           - "check-success=license/cla"
#           - "check-success=target-branch-check"
#       actions:
#           queue:
#               name: default
#               commit_message_template: |
#                   {{ title }}
#               merge_method: squash
