name: Documentation Request
description: Request improvements or report problems with documentation
labels: ["C-Documentation", "LS-Needs-Triage"]
body:
    - type: markdown
      attributes:
          value: |
              Thank you for helping us improve our documentation. Please explain what you would like to see improved.

    - type: checkboxes
      id: ensure-no-duplicates
      attributes:
          label: Please confirm the following before submitting
          options:
              - label: I have checked if someone else has already reported the same documentation problem.
                required: false

    - type: textarea
      id: documentation-problem
      attributes:
          label: Documentation Problem
          description: Describe what is missing or inaccurate in the documentation.
      validations:
          required: true

    - type: textarea
      id: suggested-improvement
      attributes:
          label: Suggested Improvement
          description: How do you think we can improve this?
      validations:
          required: false

    - type: markdown
      attributes:
          value: |
              By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/nodura/contower/blob/stable/CONTRIBUTING.md#code-of-conduct).
