# TODO: Fix this file

name: Label Pull Request

on:
    pull_request:
        types: [opened]

jobs:
    label:
        # Temporarily disabled until the script is ready
        if: false
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - run: npm install @actions/github @actions/core
            - uses: actions/github-script@v7
              with:
                  script: |
                      const script = require('./.github/scripts/label_pr.js');
                      script({github, context});
